services:
  target:
    # build: ./ # TODO use drc and mount
    image: local-mandataris
    volumes:
      - ./data/files/burgemeester-benoemingen:/uploads
    ports:
      - 8080:80
    environment:
      NOTIFICATION_CRON_PATTERN: 0 8 1 1 1-5 # basically disable
      EMAIL_FROM_MANDATARIS_EFFECTIEF: 'lokaalmandatenbeheer@vlaanderen.be' # Must be the same as EMAIL_ADDRESS in deliver-email service
      SEND_EMAIL_FOR_MANDATARIS_EFFECTIEF: false
      BESLUIT_STAGING_GRAPH: http://mu.semte.ch/graphs/besluiten-consumed # must be the same as decision-ldes-client working graph
    depends_on:
      - database
  database:
    image: semtech/sparql-parser:0.0.12
    environment:
      MU_SPARQL_ENDPOINT: 'http://virtuoso:8890/sparql'
      DATABASE_OVERLOAD_RECOVERY: 'true'
      DATABASE_COMPATIBILITY: 'Virtuoso'
      # Note: not sure wether it gets picked up properly, it is meant for healing-process which may make
      # heavy queries
      QUERY_MAX_PROCESSING_TIME: 605000
      QUERY_MAX_EXECUTION_TIME: 605000
    ports:
      - '8890:8890'
    volumes:
      - ./contract-tests/config/cl-authorization:/config
      - ./contract-tests/data/mu-auth:/data
    depends_on:
      - virtuoso
  virtuoso:
    image: redpencil/virtuoso:1.2.0-rc.1
    environment:
      SPARQL_UPDATE: 'true'
      DEFAULT_GRAPH: 'http://mu.semte.ch/application'
    volumes:
      - ./contract-tests/data/db:/data
      - ./contract-tests/config/virtuoso/virtuoso.ini:/data/virtuoso.ini # Note: on production override this setting
      - ./contract-tests/config/virtuoso/:/opt/virtuoso-scripts
  deltanotifier:
    image: semtech/mu-delta-notifier:0.3.0
    volumes:
      - ./contract-tests/config/delta:/config
  tests:
    image: node:22
    environment:
      NODE_ENV: 'development'
      MU_SPARQL_ENDPOINT: 'http://virtuoso:8890/sparql'
    ports:
      - 8666:80
    command: "bash -c 'npm install && npm run test-u'"
    working_dir: /app
    depends_on:
      - target
      - database
      - virtuoso
    volumes:
      - ./contract-tests/:/app
