services:
  mandataris:
    #build: ./
    image: semtech/mu-javascript-template:latest
    restart: no
    labels:
      - logging=true
    environment:
      TZ: Europe/Brussels
      NODE_ENV: development
      NO_BABEL_NODE: true
      EMAIL_FROM_MANDATARIS_WITHOUT_DECISION: 'lokaalmandatenbeheer@vlaanderen.be'
      SEND_EMAIL_FOR_MANDATARIS_WITHOUT_DECISION: false
      NOTIFICATION_CRON_PATTERN: '0 0 0 * * *'
    ports:
      - '8082:80'
      - '9225:9229'
    volumes:
      - ../app-lokaal-mandatenbeheer/config/mandataris:/config
      - ../app-lokaal-mandatenbeheer/data/files/burgemeester-benoemingen:/uploads
      - ./:/app
    networks:
      - debug

networks:
  debug:
    external: true
