services:
  mandataris:
    #build: ./
    image: semtech/mu-javascript-template:latest
    restart: no
    labels:
      - logging=true
    environment:
      NODE_ENV: development
      NO_BABEL_NODE: true
      EMAIL_FROM_MANDATARIS_EFFECTIEF: email@address.com
      SEND_EMAIL_FOR_MANDATARIS_EFFECTIEF: false
    ports:
      - '8082:80'
      - '9225:9229'
    volumes:
      - ../app-lokaal-mandatenbeheer/config/mandataris:/config
      - ../app-lokaal-mandatenbeheer/data/files/burgemeester-benoemingen:/uploads
      - ./:/app

    networks:
      - debug

networks:
  debug:
    external: true
