pipeline:
  lint:
    image: node:18-alpine
    commands:
      # Need git for pulling some package dependencies (erikap/sparql-client)
      - apk --no-cache add git
      - npm ci
      - npm run lint:js
  build:
    image: plugins/docker
    settings:
      repo: ${CI_REPO}
      dry_run: true
when:
  event:
    - pull_request
